# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'del_confirm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_del_confirm(object):
    def setupUi(self, del_confirm):
        del_confirm.setObjectName("del_confirm")
        del_confirm.resize(410, 234)
        self.label = QtWidgets.QLabel(del_confirm)
        self.label.setGeometry(QtCore.QRect(20, 30, 371, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.confirm_btn = QtWidgets.QPushButton(del_confirm)
        self.confirm_btn.setGeometry(QtCore.QRect(90, 170, 91, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.confirm_btn.setFont(font)
        self.confirm_btn.setObjectName("confirm_btn")
        self.cancel_btn = QtWidgets.QPushButton(del_confirm)
        self.cancel_btn.setGeometry(QtCore.QRect(240, 170, 91, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_btn.setFont(font)
        self.cancel_btn.setObjectName("cancel_btn")
        self.label_2 = QtWidgets.QLabel(del_confirm)
        self.label_2.setGeometry(QtCore.QRect(90, 100, 241, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(del_confirm)
        QtCore.QMetaObject.connectSlotsByName(del_confirm)

    def retranslateUi(self, del_confirm):
        _translate = QtCore.QCoreApplication.translate
        del_confirm.setWindowTitle(_translate("del_confirm", "确认删除"))
        self.label.setText(_translate("del_confirm", "警告！  确认删除该项数据？？"))
        self.confirm_btn.setText(_translate("del_confirm", "确认"))
        self.cancel_btn.setText(_translate("del_confirm", "取消"))
        self.label_2.setText(_translate("del_confirm", "TextLabel"))
