# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'in_info.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_in_info(object):
    def setupUi(self, in_info):
        in_info.setObjectName("in_info")
        in_info.resize(1280, 600)
        self.tableView = QtWidgets.QTableView(in_info)
        self.tableView.setGeometry(QtCore.QRect(0, 180, 1281, 361))
        self.tableView.setObjectName("tableView")
        self.groupBox = QtWidgets.QGroupBox(in_info)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 1261, 171))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 1241, 32))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.id = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.id.setFont(font)
        self.id.setObjectName("id")
        self.horizontalLayout.addWidget(self.id)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.name = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.horizontalLayout.addWidget(self.name)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.spec_lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spec_lineEdit.setFont(font)
        self.spec_lineEdit.setObjectName("spec_lineEdit")
        self.horizontalLayout.addWidget(self.spec_lineEdit)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.user_lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.user_lineEdit.setFont(font)
        self.user_lineEdit.setObjectName("user_lineEdit")
        self.horizontalLayout.addWidget(self.user_lineEdit)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.agree_lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.agree_lineEdit.setFont(font)
        self.agree_lineEdit.setObjectName("agree_lineEdit")
        self.horizontalLayout.addWidget(self.agree_lineEdit)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 71, 921, 32))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.st_dateEdit = QtWidgets.QDateEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.st_dateEdit.setFont(font)
        self.st_dateEdit.setObjectName("st_dateEdit")
        self.horizontalLayout_2.addWidget(self.st_dateEdit)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.ed_dateEdit = QtWidgets.QDateEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ed_dateEdit.setFont(font)
        self.ed_dateEdit.setObjectName("ed_dateEdit")
        self.horizontalLayout_2.addWidget(self.ed_dateEdit)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.st_num = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.st_num.setFont(font)
        self.st_num.setObjectName("st_num")
        self.horizontalLayout_2.addWidget(self.st_num)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.ed_num = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ed_num.setFont(font)
        self.ed_num.setObjectName("ed_num")
        self.horizontalLayout_2.addWidget(self.ed_num)
        self.horizontalLayout_2.setStretch(0, 10)
        self.horizontalLayout_2.setStretch(1, 10)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(3, 10)
        self.query_btn = QtWidgets.QPushButton(self.groupBox)
        self.query_btn.setGeometry(QtCore.QRect(1150, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.query_btn.setFont(font)
        self.query_btn.setObjectName("query_btn")
        self.clear_query_btn = QtWidgets.QPushButton(self.groupBox)
        self.clear_query_btn.setGeometry(QtCore.QRect(1000, 70, 131, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.clear_query_btn.setFont(font)
        self.clear_query_btn.setObjectName("clear_query_btn")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(13, 110, 1241, 61))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.del_btn = QtWidgets.QPushButton(in_info)
        self.del_btn.setGeometry(QtCore.QRect(650, 550, 131, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.del_btn.setFont(font)
        self.del_btn.setObjectName("del_btn")
        self.update_btn = QtWidgets.QPushButton(in_info)
        self.update_btn.setGeometry(QtCore.QRect(810, 550, 131, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.update_btn.setFont(font)
        self.update_btn.setObjectName("update_btn")
        self.export_excel = QtWidgets.QPushButton(in_info)
        self.export_excel.setGeometry(QtCore.QRect(970, 550, 181, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.export_excel.setFont(font)
        self.export_excel.setObjectName("export_excel")
        self.cancel_btn = QtWidgets.QPushButton(in_info)
        self.cancel_btn.setGeometry(QtCore.QRect(1180, 550, 91, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_btn.setFont(font)
        self.cancel_btn.setObjectName("cancel_btn")

        self.retranslateUi(in_info)
        QtCore.QMetaObject.connectSlotsByName(in_info)

    def retranslateUi(self, in_info):
        _translate = QtCore.QCoreApplication.translate
        in_info.setWindowTitle(_translate("in_info", "入库信息管理"))
        self.groupBox.setTitle(_translate("in_info", "筛选条件"))
        self.label.setText(_translate("in_info", "存货编码："))
        self.label_2.setText(_translate("in_info", "存货名称："))
        self.label_9.setText(_translate("in_info", "规格型号："))
        self.label_7.setText(_translate("in_info", "使用人："))
        self.label_8.setText(_translate("in_info", "令号："))
        self.label_3.setText(_translate("in_info", "入库日期范围(含):"))
        self.label_4.setText(_translate("in_info", "——"))
        self.label_5.setText(_translate("in_info", "入库数量范围(含):"))
        self.label_10.setText(_translate("in_info", "——"))
        self.query_btn.setText(_translate("in_info", "筛选"))
        self.clear_query_btn.setText(_translate("in_info", "清除筛选"))
        self.textEdit.setHtml(_translate("in_info", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:400;\">初始列出</span><span style=\" font-size:11pt; font-weight:400; color:#0000ff;\">所有入库记录</span><span style=\" font-size:11pt; font-weight:400;\">；存货编码</span><span style=\" font-size:11pt; font-weight:400; color:#0000ff;\">精确匹配</span><span style=\" font-size:11pt; font-weight:400;\">，其余项支持</span><span style=\" font-size:11pt; font-weight:400; color:#0000ff;\">模糊搜索</span><span style=\" font-size:11pt; font-weight:400;\">；某项多个输入用</span><span style=\" font-size:11pt; font-weight:400; color:#0000ff;\">%</span><span style=\" font-size:11pt; font-weight:400;\">隔开，例如：ID1%ID2%ID3；</span><span style=\" font-size:11pt; font-weight:400; color:#0000ff;\">ctrl键</span><span style=\" font-size:11pt; font-weight:400;\">可选中多行并删除，但修改时只能选中1行</span></p></body></html>"))
        self.del_btn.setText(_translate("in_info", "删除选中记录"))
        self.update_btn.setText(_translate("in_info", "修改选中记录"))
        self.export_excel.setText(_translate("in_info", "导出表中数据至Excel"))
        self.cancel_btn.setText(_translate("in_info", "关闭"))

