# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_material.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_update_material(object):
    def setupUi(self, update_material):
        update_material.setObjectName("update_material")
        update_material.resize(580, 470)
        self.verticalLayoutWidget = QtWidgets.QWidget(update_material)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 379, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.material_id_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.material_id_lineEdit.setFont(font)
        self.material_id_lineEdit.setObjectName("material_id_lineEdit")
        self.horizontalLayout_6.addWidget(self.material_id_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.material_name_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.material_name_lineEdit.setFont(font)
        self.material_name_lineEdit.setText("")
        self.material_name_lineEdit.setObjectName("material_name_lineEdit")
        self.horizontalLayout_5.addWidget(self.material_name_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.spec_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.spec_lineEdit.setFont(font)
        self.spec_lineEdit.setObjectName("spec_lineEdit")
        self.horizontalLayout_4.addWidget(self.spec_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.unit_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.unit_lineEdit.setFont(font)
        self.unit_lineEdit.setObjectName("unit_lineEdit")
        self.horizontalLayout_3.addWidget(self.unit_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.per_price_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.per_price_lineEdit.setFont(font)
        self.per_price_lineEdit.setObjectName("per_price_lineEdit")
        self.horizontalLayout_2.addWidget(self.per_price_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.position_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.position_lineEdit.setFont(font)
        self.position_lineEdit.setObjectName("position_lineEdit")
        self.horizontalLayout_8.addWidget(self.position_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.ori_num_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.ori_num_lineEdit.setFont(font)
        self.ori_num_lineEdit.setObjectName("ori_num_lineEdit")
        self.horizontalLayout.addWidget(self.ori_num_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.now_num_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.now_num_lineEdit.setFont(font)
        self.now_num_lineEdit.setObjectName("now_num_lineEdit")
        self.horizontalLayout_7.addWidget(self.now_num_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.both_confirm_pushButton = QtWidgets.QPushButton(update_material)
        self.both_confirm_pushButton.setGeometry(QtCore.QRect(440, 160, 111, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.both_confirm_pushButton.setFont(font)
        self.both_confirm_pushButton.setObjectName("both_confirm_pushButton")
        self.cancel_pushButton = QtWidgets.QPushButton(update_material)
        self.cancel_pushButton.setGeometry(QtCore.QRect(440, 250, 111, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_pushButton.setFont(font)
        self.cancel_pushButton.setObjectName("cancel_pushButton")

        self.retranslateUi(update_material)
        QtCore.QMetaObject.connectSlotsByName(update_material)

    def retranslateUi(self, update_material):
        _translate = QtCore.QCoreApplication.translate
        update_material.setWindowTitle(_translate("update_material", "确认修改存货信息"))
        self.label_2.setText(_translate("update_material", "存货编码："))
        self.label_3.setText(_translate("update_material", "存货名称："))
        self.label.setText(_translate("update_material", "规格型号："))
        self.label_4.setText(_translate("update_material", "计量单位："))
        self.label_6.setText(_translate("update_material", "单价(元):"))
        self.label_8.setText(_translate("update_material", "库存位置："))
        self.label_5.setText(_translate("update_material", "期初数量："))
        self.label_7.setText(_translate("update_material", "结存数量："))
        self.both_confirm_pushButton.setText(_translate("update_material", "修改存货"))
        self.cancel_pushButton.setText(_translate("update_material", "关闭"))

